all: 1.9.2 1.12.6 1.18.1 tip

1.9.2:
	@echo "Making 1.9.2.."
	$(MAKE) -C 1.9.2

1.12.6:
	@echo "Making 1.12.6.."
	$(MAKE) -C 1.12.6

1.18.1:
	@echo "Making 1.18.1.."
	$(MAKE) -C 1.18.1

tip:
	@echo "Making tip.."
	$(MAKE) -C tip

.PHONY : all 1.9.2 1.12.6 1.18.1 tip
