FROM hkjn/golang:tip

ARG goarch
ARG version

ENV CGO_ENABLED=0 \
    GOOS=linux \
    GOARCH=${goarch} \
    VERSION=${version}

WORKDIR /home/go/src/hkjn.me/lnmon/
COPY *.go ./
COPY ["vendor", "./vendor"]
USER root
RUN chown -R go:go /home/go/bin
USER go

RUN go vet && \
    go install -ldflags="-X main.lnmonVersion=${VERSION}"

CMD echo "Binary available in ${GOPATH}/bin: $(ls -hsal ${GOPATH}/bin)"
