#!/usr/bin/env bash
#
# Lock the ironkey via the container with 32bit libs inside.
#

set -euo pipefail

fatal() {
  echo "[ $(basename "$0") ] FATAL: $*" >&2
  exit 1
}

[[ -e "/dev/sr0" ]] || fatal "No /dev/sr0 device present."

docker run --device /dev/sr0 --rm -it --privileged hkjn/ironkey lock
