groups:
  - name: system
    rules:
    - record: instance_system:node_disk_bytes_read:sum_rate5m
      expr: sum(rate(node_disk_bytes_read[5m])) by (group, kind, job, instance)
    - record: instance_system:node_disk_bytes_written:sum_rate5m
      expr: sum(rate(node_disk_bytes_written[5m])) by (group, kind, job, instance)
  - name: lightningd
    rules:
    - record: job_lightningd:channel_balances_msatoshi:max
      expr: max(lightningd_channel_balances_msatoshi) by (direction, node_id)
    - record: job_lightningd:channel_capacities_msatoshi:max
      expr: max(lightningd_channel_capacities_msatoshi) by (node_id)
