groups:
  - name: system
    rules:
    - record: instance_system:node_disk_bytes_read:sum_rate5m
      expr: sum(rate(node_disk_bytes_read[5m])) by (group, kind, job, instance)
    - record: instance_system:node_disk_bytes_written:sum_rate5m
      expr: sum(rate(node_disk_bytes_written[5m])) by (group, kind, job, instance)
    - record: instance_system:node_network_transmit_bytes:sum_rate5m
      expr: sum(rate(node_network_transmit_bytes[5m])) by (group, kind, job, instance)
    - record: instance_system:node_network_receive_bytes:sum_rate5m
      expr: sum(rate(node_network_receive_bytes[5m])) by (group, kind, job, instance)

  - name: lightningd
    rules:
    - record: job_lightningd:channel_balances_msatoshi:sum
      expr: sum(lightningd_channel_balances_msatoshi) by (direction, node_id, state)
    - record: job_lightningd:channel_capacities_msatoshi:sum
      expr: sum(lightningd_channel_capacities_msatoshi) by (node_id, state)
    - record: job_lightningd:channel_balances_normal_btc:sum
      expr: sum(lightningd_channel_balances_msatoshi{state="CHANNELD_NORMAL"}) by (direction, node_id)/100000000000
    - record: job_lightningd:channel_balances_normal_to_us_btc:sum
      expr: sum(lightningd_channel_balances_msatoshi{state="CHANNELD_NORMAL",direction="to_us"}) by (node_id)/100000000000
    - record: job_lightningd:channel_balances_normal_to_them_btc:sum
      expr: sum(lightningd_channel_balances_msatoshi{state="CHANNELD_NORMAL",direction="to_them"}) by (node_id)/100000000000
    - record: job_lightningd:channel_capacities_normal_btc:sum
      expr: sum(lightningd_channel_capacities_msatoshi{state="CHANNELD_NORMAL"}) by (node_id)/100000000000
    - record: job_lightningd:aliases:sum
      expr: sum(lightningd_aliases) by (node_id, alias)
    - record: job_lightningd:total_funds_btc
      expr: sum(lightningd_total_funds)/100000000
