#!/bin/bash
#
# Helper script to download, verify and print hash of Tor browser release.
#
set -euo pipefail

VERSION=${1:-""}
TMP_DIR=$(mktemp -d)

if [[ ! "${VERSION}" ]]; then
  echo "FATAL: no VERSION specified" >&2
  exit 1
fi

cd "${TMP_DIR}"
curl -LO https://dist.torproject.org/torbrowser/${VERSION}/sha256sums-signed-build.txt
curl -LO https://dist.torproject.org/torbrowser/${VERSION}/sha256sums-signed-build.txt.asc
gpg --verify sha256sums-signed-build.txt.asc
grep linux64-${VERSION}_en-US.tar.xz sha256sums-signed-build.txt