init:
	docker run --rm -it -v $(CURDIR):/home/tfuser hkjn/terraform:0.12.1 init

plan:
	docker run --rm -it -v $(CURDIR):/home/tfuser hkjn/terraform:0.12.1 plan

apply:
	docker run --rm -it -v $(CURDIR):/home/tfuser hkjn/terraform:0.12.1 apply
