{
 "title": "prom-manual",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Rate of successful checks",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(github_reached_count[15m])",
     "legendFormat": "Github.com reached"
    },
    {
     "expr": "rate(tor_status_reached_count[15m])",
     "legendFormat": "Tor reached"
    },
    {
     "expr": "rate(wasabi_onion_reached_count[15m])",
     "legendFormat": "Wasabi price service reached"
    },
    {
     "expr": "rate(frankenbox_sshd_onion_reached_count[15m])",
     "legendFormat": "Frankenbox sshd reached"
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Sum of CPU usage rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total{mode=\"iowait\"}[15m]))",
     "legendFormat": "iowait"
    },
    {
     "expr": "sum(rate(node_cpu_seconds_total{mode=\"irq\"}[15m]))",
     "legendFormat": "irq"
    },
    {
     "expr": "sum(rate(node_cpu_seconds_total{mode=\"nice\"}[15m]))",
     "legendFormat": "nice"
    },
    {
     "expr": "sum(rate(node_cpu_seconds_total{mode=\"softirq\"}[15m]))",
     "legendFormat": "softirq"
    },
    {
     "expr": "sum(rate(node_cpu_seconds_total{mode=\"steal\"}[15m]))",
     "legendFormat": "steal"
    },
    {
     "expr": "sum(rate(node_cpu_seconds_total{mode=\"system\"}[15m]))",
     "legendFormat": "system"
    },
    {
     "expr": "sum(rate(node_cpu_seconds_total{mode=\"user\"}[15m]))",
     "legendFormat": "user"
    }
   ]
  },
  {
   "title": "Rate of IO time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_io_time_seconds_total[15m])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Battery percent",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "100.0*energy_now/energy_full", "legendFormat": "Battery" }
   ]
  },
  { "title": "Bitcoin", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Wasabi price",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "wasabi_sat_per_usd", "legendFormat": "Wasabi sat/USD" }
   ]
  }
 ]
}