init:
	docker run --rm -it -v $(CURDIR):/home/tfuser hkjn/terraform init

plan:
	docker run --rm -it -v $(CURDIR):/home/tfuser hkjn/terraform plan

apply:
	docker run --rm -it -v $(CURDIR):/home/tfuser hkjn/terraform apply
