#
# Build image for fileserver.
#
FROM hkjn/golang

ENV CGO_ENABLED=0
WORKDIR /home/go/src/hkjn.me/fileserver/
COPY *.go ./
COPY ["vendor", "./vendor"]
RUN go vet && \
    go install
USER root
WORKDIR /build
CMD ls -hsal && mv -v /home/go/bin/fileserver ./
