FROM hkjn/golang:tip

ARG goarch

ENV CGO_ENABLED=0 \
    GOOS=linux \
    GOARCH=${goarch}

WORKDIR /home/go/src/hkjn.me/src/lnmon/
COPY *.go ./
COPY ["vendor", "./vendor"]
USER root
RUN chown -R go:go /home/go/bin
USER go

RUN go vet && \
    go install

CMD echo "Binary available in ${GOPATH}/bin: $(ls -hsal ${GOPATH}/bin)"
